version: "3.3"

services:
  blue:
    image: ehazlett/docker-demo:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - Title=Blue
    ports:
      - target: 8080
        published: 80
        protocol: tcp
